"""Read-only access to the normalized item dataset produced by the importer.

The dataset is `data/normalized/items_normalized.json`, generated by
`scripts/import_datamining.py` from the `vendor/ffxiv-datamining` submodule.
See docs/FFXIV_Pipeline.md for the full pipeline.

Coordinates come from ExportedGatheringPoint, where the exported index is
`GatheringPoint."#" - 30000`. Gathering points that were never exported have
`x`/`y` set to null and are reported as `has_coords = False`.
"""
from __future__ import annotations

import json
import os
import threading
from typing import Any, Dict, List, Optional

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_DATA_PATH = os.path.join(REPO_ROOT, "data", "normalized", "items_normalized.json")

_lock = threading.Lock()
_cache: Dict[str, Dict[int, Dict[str, Any]]] = {}


class DatasetNotFoundError(RuntimeError):
    """Raised when the normalized dataset file is missing."""


def _resolve_path(path: Optional[str]) -> str:
    return os.path.abspath(path or os.environ.get("FFXIV_DATA_PATH") or DEFAULT_DATA_PATH)


def load_items(path: Optional[str] = None) -> Dict[int, Dict[str, Any]]:
    """Load the normalized dataset, keyed by integer item id.

    The result is cached per resolved path; the file is read once per process.
    """
    resolved = _resolve_path(path)
    with _lock:
        cached = _cache.get(resolved)
        if cached is not None:
            return cached

        if not os.path.exists(resolved):
            raise DatasetNotFoundError(
                f"Normalized dataset not found at {resolved}. "
                "Generate it with: python scripts/import_datamining.py"
            )

        with open(resolved, "r", encoding="utf-8") as fh:
            raw = json.load(fh)

        items: Dict[int, Dict[str, Any]] = {}
        for key, value in raw.items():
            try:
                items[int(key)] = value
            except (TypeError, ValueError):
                continue

        _cache[resolved] = items
        return items


def get_item(item_id: int, path: Optional[str] = None) -> Optional[Dict[str, Any]]:
    """Return one item by id, or None when the id is unknown."""
    return load_items(path).get(int(item_id))


def summarize_item(item_id: int, item: Dict[str, Any]) -> Dict[str, Any]:
    """Return a compact record for an item, counting its gathering nodes."""
    nodes = item.get("nodes") or []
    has_coords = any(n.get("x") is not None and n.get("y") is not None for n in nodes)
    return {
        "id": item_id,
        "name": item.get("name", ""),
        "node_count": len(nodes),
        "has_coords": has_coords,
    }


def search_items(
    query: str,
    path: Optional[str] = None,
    limit: int = 20,
) -> List[Dict[str, Any]]:
    """Case-insensitive search over item names.

    Exact (case-folded) matches rank first, then names starting with the query,
    then remaining substring matches, each group sorted alphabetically.
    """
    items = load_items(path)
    needle = (query or "").strip().casefold()
    if not needle:
        return []

    exact: List[Dict[str, Any]] = []
    startswith: List[Dict[str, Any]] = []
    contains: List[Dict[str, Any]] = []

    for item_id, item in items.items():
        folded = (item.get("name") or "").casefold()
        entry = summarize_item(item_id, item)
        if folded == needle:
            exact.append(entry)
        elif folded.startswith(needle):
            startswith.append(entry)
        elif needle in folded:
            contains.append(entry)

    for group in (exact, startswith, contains):
        group.sort(key=lambda e: e["name"])
    return (exact + startswith + contains)[: max(0, limit)]


def find_items_by_name(name: str, path: Optional[str] = None) -> List[Dict[str, Any]]:
    """Return every item whose name matches `name` exactly, ignoring case.

    Unlike `search_items`, this is not a substring match: looking up "Laurel"
    returns Laurel and not "Lover's Laurel".
    """
    items = load_items(path)
    needle = (name or "").strip().casefold()
    if not needle:
        return []
    matches = [
        summarize_item(item_id, item)
        for item_id, item in items.items()
        if (item.get("name") or "").casefold() == needle
    ]
    matches.sort(key=lambda e: e["id"])
    return matches


def format_node(node: Dict[str, Any]) -> str:
    """Render one gathering node as a single human-readable line."""
    place = node.get("place_name") or node.get("territory_name") or "unknown area"
    x, y = node.get("x"), node.get("y")
    if x is None or y is None:
        return f"{place} (coordinates not exported)"
    return f"{place} (X: {x}, Y: {y})"


def format_chat_reply(item_name: str, item: Dict[str, Any]) -> str:
    """Build the Twitch chat reply for an item lookup."""
    nodes = item.get("nodes") or []
    if not nodes:
        return f"[Gather] {item_name} can be gathered, but no gathering data was found."

    located = [n for n in nodes if n.get("x") is not None and n.get("y") is not None]
    if not located:
        return (
            f"[Gather] {item_name} was found in {len(nodes)} spot(s), "
            "but their coordinates are not available in the exported data."
        )

    places: List[str] = []
    for node in located:
        place = node.get("place_name") or node.get("territory_name") or "unknown area"
        if place not in places:
            places.append(place)

    lines = [f"[Gather] {item_name} can be gathered in: {', '.join(places)}."]
    lines.extend(f" - {format_node(n)}" for n in located[:5])
    if len(located) > 5:
        lines.append(f" - ...and {len(located) - 5} more location(s).")
    return "\n".join(lines)
